version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - ENGINE=django.db.backends.mysql
      - NAME=Rostro_DB
      - USER=rostro_test
      - PASSWORD=9vxL4_0pCa.58
      - HOST=db-rostro-mysql.cvd6cndsisc1.us-east-1.rds.amazonaws.com
      - PORT=3306
    depends_on:
      - db

  db:
    #image: postgres:13-alpine
    build:
      context: .
    volumes:
      - dev-db-data:/var/lib/mysql
    environment:
      - MYSQL_DB=Rostro_DB
      - MYSQL_USER=rostro_test
      - MYSQL_PASSWORD=9vxL4_0pCa.58

volumes:
  dev-db-data:
  dev-static-data: