# Generated by Django 3.2.15 on 2022-09-12 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:'+999999999'. Upto 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('street_address', models.CharField(max_length=255)),
                ('city_address', models.CharField(max_length=255)),
                ('zipcode_address', models.CharField(max_length=255)),
                ('state_address', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Non-binary/non-conforming', 'Non-binary/non-conforming'), ('Prefer not to respond', 'Prefer not to respond')], default='Prefer not to respond', max_length=50)),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Physical Therapist', 'Physical Therapist')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('med_list', models.TextField(blank=True)),
                ('age', models.IntegerField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:'+999999999'. Upto 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_of_birth', models.DateField(null=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city_address', models.CharField(blank=True, max_length=255)),
                ('zipcode_address', models.CharField(blank=True, max_length=255)),
                ('state_address', models.CharField(blank=True, max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Non-binary/non-conforming', 'Non-binary/non-conforming'), ('Prefer not to respond', 'Prefer not to respond')], default='Prefer not to respond', max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('emergency_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:'+999999999'. Upto 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('relationship', models.CharField(choices=[('Spouse', 'Spouse'), ('Mother', 'Mother'), ('Father', 'Father'), ('Children', 'Children'), ('Friend', 'Friend'), ('Not Applicable', 'PNot Applicable')], default='Not Applicable', max_length=50)),
                ('is_in_hospital', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
