# Generated by Django 3.2.15 on 2022-09-10 06:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.EmailField(max_length=255, unique=True)),
                ('patient_first_name', models.CharField(max_length=255)),
                ('patient_last_name', models.CharField(max_length=255)),
                ('patient_description', models.TextField(blank=True)),
                ('patient_med_list', models.TextField(blank=True)),
                ('patient_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:'+999999999'. Upto 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('patient_date_of_birth', models.DateField(max_length=8)),
                ('patient_street_address', models.CharField(max_length=255)),
                ('patient_city_address', models.CharField(max_length=255)),
                ('patient_zipcode_address', models.CharField(max_length=255)),
                ('patient_state_address', models.CharField(max_length=255)),
                ('patient_creation_date', models.DateTimeField(auto_now_add=True)),
                ('patient_modified_date', models.DateTimeField(auto_now=True)),
                ('patient_link', models.CharField(blank=True, max_length=255)),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Non-binary/non-conforming', 'Non-binary/non-conforming'), ('Prefer not to respond', 'Prefer not to respond')], default='Prefer not to respond', max_length=50)),
                ('emergency_contact_email', models.EmailField(max_length=255, unique=True)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:'+999999999'. Upto 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('relationship', models.CharField(choices=[('Spouse', 'Spouse'), ('Mother', 'Mother'), ('Father', 'Father'), ('Children', 'Children'), ('Friend', 'Friend'), ('Not Applicable', 'PNot Applicable')], default='Not Applicable', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
