# Generated by Django 3.2.15 on 2022-09-11 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='emergency_email',
        ),
    ]
