# Generated by Django 3.2.15 on 2022-09-14 01:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220912_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.patients_image_file_path),
        ),
    ]
