# Generated by Django 3.2.15 on 2022-09-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
