# Generated by Django 3.2.15 on 2022-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_patient_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_email',
            field=models.EmailField(max_length=255),
        ),
    ]
